Repository arjunatapadkar/codeteria, pull requests merged in 2024-10, with the labels that each got.

#11 fix: Making The Navbar sticky
  src/App.jsx
  src/pages/Homepage.jsx
Labels: good first issue, gssoc-ext, level1

#16 create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc24-extd

#14 scroll bar feature added : the scroll bar added and #1 completed as assigned to me
  src/App.jsx
Labels: good first issue, level1, gssoc24-extd

#28 Working Playground Page Added & API Integration for Running Code
  .env
  src/App.jsx
  src/pages/playground/Playground.jsx
Labels: gssoc24-extd, gssoc, level3, New feature

#50 hamburger navbar feat added
  package-lock.json
  package.json
  src/App.jsx
  src/components/MainNavbar.jsx
  src/main.jsx
  src/pages/Homepage.jsx
  src/pages/playground/Playground.jsx
  src/pages/upcoming.jsx
Labels: bug, gssoc-ext, gssoc24-extd, gssoc, level2

#56 Fixed Position of ChatBot + Enhanced Close Logic + Bug Fixed For Close Button of WebChat
  src/App.jsx
  src/components/chatbot/Chat.jsx
  src/pages/Homepage.jsx
Labels: gssoc-ext, level2

#59 Updated README.md
  README.md
Labels: good first issue, gssoc-ext, level1, gssoc24-extd, gssoc, gssoc-extd

#66 implemented smooth scroll
  src/pages/Homepage.jsx
Labels: gssoc-ext, level1, gssoc24-extd, gssoc, gssoc-extd

#68 added auto play on code snippets
  src/pages/Homepage.jsx
Labels: gssoc-ext, level1, gssoc24-extd, gssoc, gssoc-extd

#73 Revamp Playground UI for Improved UX
  .env
  package-lock.json
  package.json
  src/pages/playground/Playground.jsx
  src/pages/playground/playground.css
Labels: enhancement, gssoc-ext, gssoc24-extd, gssoc, level3, gssoc-extd

#78 modified error 404 only
  src/pages/ErrorPage.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#84 Added Icons on Footer Section issue #61
  src/pages/Homepage.jsx
  src/pages/styles.js
  src/styles.js
Labels: gssoc-ext, level1, hacktoberfest-accepted

#91 making navbar responsive issue number #74
  package-lock.json
  src/components/MainNavbar.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#105 enhanced footer
  src/pages/Homepage.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#104 Responsive Contact Us Section Added
  src/components/Contact.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#72 Contribution: Fixed the quick links in the footer (not proper mapping) && fixed readme.md (command for running local dev enviornment)
  .hintrc
  README.md
  src/index.css
  src/pages/Homepage.jsx
  src/pages/cheatsheet/Cheatsheet.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#117 Add new feature: Sharing Snippets
  package-lock.json
  package.json
  src/pages/playground/Playground.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#124 Nav items color on hover is now changed after clicking start coding
  src/components/landing page/Navbarm.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#133 custom cursor added
  package-lock.json
  package.json
  src/App.jsx
  src/index.css
  src/pages/Homepage.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#113 Added DS Problem
  src/App.jsx
  src/context/apiContext.jsx
  src/pages/Homepage.jsx
  src/pages/dsproblem/DSProblem.jsx
  src/pages/interview/InterviewPrep.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#147 Made the marquee tag stops on hovering to make better readability for the users.
  src/index.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#150 Improve UI of testimonials and add animation
  src/pages/Homepage.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#152 Fixes #146 Data Leak Bug Fixed
  .env
  src/context/apiContext.jsx
  src/pages/cheatsheet/Cheatsheet.jsx
  src/pages/interview/ChallengeDetail.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#164 added terms and conditions
  package-lock.json
  src/App.jsx
  src/components/core/Footer.jsx
  src/pages/terms/terms.css
  src/pages/terms/terms.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#166 feed back star button added
  src/components/starrating.jsx
  src/pages/Homepage.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#183 Enhanced Footer with Hover Effects and 3D Animation for Social Media #181
  src/components/core/Footer.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#158 solved #121 Created Quiz page
  src/App.jsx
  src/main.jsx
  src/pages/Homepage.jsx
  src/pages/quizes/quiz.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#157 Solved the issue #111
  package-lock.json
  package.json
  src/pages/ErrorPage.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#192 added subscription letter
  package-lock.json
  package.json
  src/pages/Homepage.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#195 Try it Yourself Button Implemented Redirect to Playground
  src/components/Section.jsx
  src/pages/playground/Playground.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#194 Added different Payment plan options
  src/App.jsx
  src/pages/Homepage.jsx
  src/pages/pro/Pro.jsx
  src/pages/upcoming.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#208 enhanced quiz page
  src/App.jsx
  src/pages/Homepage.jsx
  src/pages/quizzes/Quiz.jsx
Labels: gssoc-ext, level2, hacktoberfest-accepted

#210 issue#173 fixed
  src/App.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#214 [Bug]: Updated code to make logo center of '/cheats route'
  src/components/landing page/Navbarm.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#221 Add revamp to the crousel make it more appealing
  src/pages/Homepage.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#222 Added color to Cursor on Hover over Chatbot
  src/components/chatbot/Chat.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#225 Fixed Product Page OverFlow under Navabar
  src/pages/products/product.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#230 Added Upload File Button & Implementation Logic on Playground
  src/pages/playground/Playground.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#241 Added Execution Metrics Time & Memory
  src/pages/playground/Playground.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#245 Fix : Missing Border for Email Input Field in Newsletter Subscription
  src/pages/Homepage.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#249 Try it Yourself Language Based Selection
  src/components/Section.jsx
  src/pages/cheatsheet/Cheatsheet.jsx
  src/pages/playground/Playground.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#253 Fixed MachineCoding Page Frontend
  src/components/core/Footer.jsx
  src/pages/interview/ChallengeDetail.jsx
  src/pages/interview/machineCoding.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#274 added intro page on initial loading
  src/App.jsx
  src/components/Intro.css
  src/components/Intro.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#276 enhanced the terms and conditions page
  src/pages/terms/Terms.jsx
  src/pages/terms/terms.css
Labels: gssoc-ext, level2, hacktoberfest-accepted
