Repository arjunatapadkar/codeteria, pull requests merged in 2024-11, with the labels that each got.

#277 Offline First Experience with Caching and Sync Status Indicator
  public/offline.html
  public/service-worker.js
  src/main.jsx
Labels: gssoc-ext, level3, hacktoberfest-accepted

#281 solved overlapping issue with chatbot
  src/components/chatbot/Chat.jsx
Labels: gssoc-ext, level1, hacktoberfest-accepted

#283 added community page
  src/App.jsx
  src/components/MainNavbar.jsx
  src/pages/community/Community.jsx
  src/pages/community/community.css
Labels: gssoc-ext, level2, hacktoberfest-accepted
